### ISSUE TITLE
Clarify `bbox` param

### ISSUE THREAD

**Issue by tordans** [derhuerst/query-fis-broker-wfs#13]
It would be great if the docs helped to understand the `bbox` param (`const bbox = [387000, 5812000, 386000, 5813000]`).

My first error was to give it a "regular" bbox like `[
  [13.088398, 52.33832],
  [13.76116, 52.33832],
  [13.76116, 52.675454],
  [13.088398, 52.675454],
  [13.088398, 52.33832],
]` which resulted in a empty error message. 

```
56 | 		const err = new Error(res.statusText)
57 | 		err.statusCode = res.status
         ^
error: Error
 url: "https://gdi.berlin.de/services/wfs/fussgaengernetz?service=WFS&version=2.0.0&request=GetFeature&typeNames=fussgaengernetz%3Ab_strassenelemente&bbox=13.088398%2C52.33832%2C13.76116%2C52.33832%2C13.76116%2C52.675454%2C13.088398%2C52.675454%2C13.088398%2C52.33832"

      at /Users/…/datenabgleich/node_modules/query-fis-broker-wfs/lib/request.js:57:6
```

The [generated URL](https://gdi.berlin.de/services/wfs/fussgaengernetz?service=WFS&version=2.0.0&request=GetFeature&typeNames=fussgaengernetz%3Ab_strassenelemente&bbox=13.088398%2C52.33832%2C13.76116%2C52.33832%2C13.76116%2C52.675454%2C13.088398%2C52.675454%2C13.088398%2C52.33832) was talking about " No authority was defined for code … AUTHORITY:NUMBER"

---

**My suggested change is:** Update the readme to explain the format of the bbox and how to get it. For example, how can I use something like https://hanshack.com/geotools/gimmegeodata/ to get the right format? Or, how can I just say "give me the min/max bounds for this service".

**Comment by tordans** [comment]
I will close this here because I don't thinks the open issue will help in any way. I started working on a processing pipeline in https://github.com/osmberlin/datenabgleich

**Comment by derhuerst** [comment]
Apparently, the coordinates need to be in the layer's native coordinate reference system (CRS), which can be obtained using `(await getCapabilities(…)).layers[0].crs`.
