### ISSUE TITLE
`TypeError: undefined is not an object (evaluating 'state.buffer[0].length')`

### ISSUE THREAD

**Issue by tordans** [derhuerst/query-fis-broker-wfs#14]
I was trying to run the package with bun.sh and got this error. When I remove the fetch overwrite `import _createFetch from 'fetch-ponyfill' const {fetch} = _createFetch()` the error disappears but a new error shows up related to the XML package.

The code I ran is at https://github.com/osmberlin/datenabgleich/commit/625546260d07bb99f86ab00e653fdc78f977519b 

```
% bun run data/Fußgängernetz/pull.ts
11 |     // Since node 6.3.0 state.buffer is a BufferList not an array
12 |     if (state.buffer.head) {
13 |       return state.buffer.head.data.length
14 |     }
15 |
16 |     return state.buffer[0].length
               ^
TypeError: undefined is not an object (evaluating 'state.buffer[0].length')
      at getStateLength (/Users/fmc/Development/OSM/datenabgleich/node_modules/stream-shift/index.js:16:11)
      at shift (/Users/fmc/Development/OSM/datenabgleich/node_modules/stream-shift/index.js:6:98)
      at /Users/fmc/Development/OSM/datenabgleich/node_modules/duplexify/index.js:168:34
      at onreadable (/Users/fmc/Development/OSM/datenabgleich/node_modules/duplexify/index.js:134:4)
      at processTicksAndRejections (:55:76)


```

**Comment by tordans** [comment]
I will close this here because I don't thinks the open issue will help in any way. I started working on a processing pipeline in https://github.com/osmberlin/datenabgleich

**Comment by derhuerst** [comment]
Thanks for reporting this!

It looks like bun.sh does not provide the Stream APIs expected by `stream-shift` – or `stream-shift` is not compatible with bun.sh, depends on your perspective.

Given that I don't officially support Bun with this package, [only Node.js 18+](https://github.com/derhuerst/query-fis-broker-wfs/blob/3f6b9c91ebdff7fca74e06ac9d8571c060db487e/package.json#L26-L28), this is out of scope of this repo, unfortunately. Have you tried running your code with Node?
